services:

  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome # Official image from AdGuard https://hub.docker.com/r/adguard/adguardhome
    ports:

      - "53:53/tcp"           # DNS
      - "53:53/udp"           # DNS

      - "8081:80/tcp"         # Web interface      
#     - "443:443/tcp"         # Web interface
      - "3000:3000/tcp"       # Web interface for installation

#      - 67/udp      # For use as DCHP server
#      - 68/tcp      # For use as DCHP server
#      - 68/udp      # For use as DCHP server
#      - 853/tcp     # For DNS over TLS
      
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf

    restart: unless-stopped