version: "2.1"

services:

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    
    environment:
      - PUID=1000
      - PGID=1000
 
      - TZ=Europe/Minsk
 
      - TRANSMISSION_WEB_HOME=/transmission-web-control/   # UI Option
                                                    #  /combustion-release/
                                                    #  /transmission-web-control/
                                                    #  /kettu/
                                                    #  /flood-for-transmission/
                                                    #  /transmissionic/
#      - USER=username #optional
#      - PASS=password #optional
#      - WHITELIST=iplist #optional
#      - PEERPORT=peerport #optional
#      - HOST_WHITELIST=dnsname list #optional
    
    volumes:
      - ./config:/config                            
      - ./downloads:/downloads                      # symlink 
      - ./watch:/watch                              # symlink
    
    ports:
      - 9091:9091             # WebUI
      - 51413:51413           # Torrent Port TCP
      - 51413:51413/udp       # Torrent Port UDP
    
    restart: unless-stopped